baseURL = "https://blog.hozi.tech/"
languageCode = "en-us"
title = "BLOG.HOZI"
SectionPagesMenu = "main"
enableGitInfo = true
theme= "capsule"
pygmentsCodefences = true # ```で囲んだコードをハイライトする設定
enableEmoji = true
