baseURL = "https://blog.hozi.tech/"
languageCode = "en-us"
title = "話があるんだ。どうしても言わなくちゃならない、大事な…"
SectionPagesMenu = "main"
enableGitInfo = true
theme= "capsule"
pygmentsCodefences = true # ```で囲んだコードをハイライトする設定
enableEmoji = true